application:
  message: 应用消息
  debug: true
  
# Customizing the management endpoint paths and server port
# management:
  # port: 8081
  # context-path: /manage
  
# Server settings (ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  # 服务器session过期时间
  session:
    timeout: 300
  # contextPath: /test
  # 这里不要直接这样写，默认本来就是根目录 contextPath: /

  # Tomcat specifics
  tomcat:
    protocolHeader: x-forwarded-proto
    remoteIpHeader: x-forwarded-for
    basedir:
    backgroundProcessorDelay: 30 # secs
    
spring:
  datasource:
    url: jdbc:mysql://localhost/test?characterEncoding=utf8
    username: dbuser
    password: dbpass
    tomcat:
      max-active: 20
    # driver-class: com.mysql.jdbc.Driver
  jpa:
    showSql: true
  mongodb:
    host: localhost
    port: 27017
    database: spring
  mail:
    host: smtp.exmail.qq.com
    port: 25
    username: username@qq.com
    password: password
    user:
      from: username@qq.com
  resources:
    staticLocations: /static
